---
abstract: 'Simple Object Relational Mapping for Dancer'
author:
  - 'Al Newkirk <awncorp@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101241'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-ORMesque
recommends: {}
requires:
  DBIx::Simple: 0
  Dancer::Plugin::Database: 0
  SQL::Abstract: 0
  SQL::Interp: 0
version: 0.0100
